name: Auto Check Kho Nhua HVT

on:
  schedule:
    # Chạy tự động mỗi 15 phút/lần
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Script
        env:
          KHO_COOKIE: ${{ secrets.KHO_COOKIE }}
          COOKIE_HCM: ${{ secrets.COOKIE_HCM }}
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
        run: python main.py
